spring.application.name=demo

###############################################
### DATABASE CONNECTIVITY CONFIGURATIONS ###
###############################################
database.ip = ${DB_IP:}
database.port = ${DB_PORT:5432}
database.user = ${DB_USER:postgres}
database.password = ${DB_PASSWORD:12345}
database.name = ${DB_DBNAME:springdb}

spring.sql.init.platform=postgres
spring.datasource.url = jdbc:postgresql://ep-spring-dew-ahk27gbv.c-3.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_ePFH7QwBNcy1&sslmode=require&channelBinding=require
spring.datasource.username = ${database.user}
spring.datasource.password = ${database.password}

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.show_sql=true
server.tomcat.threads.max = 1
###############################################
### LOGGING CONFIGURATIONS ###
###############################################
logging.level.root=warn
logging.level.org.springframework=warn
logging.level.ro.tuc=warn
###############################################
### EMBEDDED TOMCAT CONFIGURATIONS ###
###############################################
server.port=${PORT:8080}
